#!/bin/bash 

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPTS_DIR}/util"

# https://forums.docker.com/t/how-to-turn-off-the-whats-new-message/140860/7
export DOCKER_CLI_HINTS=false

export SCYLLA_BACKEND=default
export DOCKER_PLATFORM="linux/amd64"

if [ "$(uname)" == "Darwin" ]; then
    SCYLLA_BACKEND=epoll
    DOCKER_PLATFORM="linux/arm64/v8"
fi

echo
echo "Using ScyllaDB backend: ${SCYLLA_BACKEND} on platform: ${DOCKER_PLATFORM}"
echo

usage() {
    echo "docker system usage"  
    # if full run ops/prune
    docker system df # --format json | jq '.Reclaimable'
}

up() {
    echo 
    echo "Bringing up ScyllaDB cluster ..."
    echo

    docker-compose -f "${SCRIPTS_DIR}/compose.yml" up -d --wait

    "${SCRIPTS_DIR}/exec" "DESCRIBE CLUSTER"

    # scripts/exec "SELECT host_id FROM system.local;QUIT;"
    docker exec -it "scylla-node1" nodetool status
    echo 
}

down() {
    echo 
    echo "Bringing down ScyllaDB cluster ..."
    echo

    # -v prunes the compose anonymous volumes
    docker-compose -f "${SCRIPTS_DIR}/compose.yml" down -v
    echo 
}

cqlsh() {
    docker exec -it scylla-node1 cqlsh
}

help() {
    echo
    echo "Usage: $0 <up|down|cqlsh|usage|help>"
    echo
    echo "  up       - Bring up ScyllaDB cluster"
    echo "  down     - Bring down ScyllaDB cluster"
    echo "  cqlsh    - Open cqlsh shell to the cluster"
    echo "  usage    - Show docker system usage"
    echo "  help     - Show this help message"
    echo
}

action=${1:-}
if [ -z "$action" ]; then
    help
    exit 1
fi

case $action in
  up)
    up
  ;;
  down)
    down
  ;;
  cqlsh)
    cqlsh
  ;;
  usage)
    usage
  ;;
  help)
    help
  ;;
esac