#!/bin/bash 

# check
# checks the ScyllaDB cluster by running describe cluster from the host
# Usage: ./scripts/check

set -euo pipefail

# Connect to ScyllaDB cluster from containerrunning on scyllau-net network
# docker run -it --rm --network scyllau-net scylladb/scylla-cqlsh -e 'DESCRIBE CLUSTER' scyllaU1 9042 # --help

# connect from the host
# notice you don't have to provide the process name (cqlsh) as the entrypoint
docker run -it --rm --network host scylladb/scylla-cqlsh -e 'DESCRIBE CLUSTER' localhost 9042 # --help
