#!/bin/bash
set -eou pipefail

OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(realpath "${OPS_DIR}/../scripts")"

# For Development, Use --reactor-backend=epoll: For development environments on macOS, consider using the –reactor-backend=epoll option when starting ScyllaDB in Docker. This can be necessary because the default linux-aio backend might not function as expected on macOS
# https://docs.scylladb.com/manual/stable/operating-scylla/procedures/tips/best-practices-scylla-on-docker.html
# https://hub.docker.com/r/scylladb/scylla

# https://forums.docker.com/t/how-to-turn-off-the-whats-new-message/140860/7
export DOCKER_CLI_HINTS=false

SCYLLA_NAME=scyllaU
SCYLLA_BACKEND=default
DOCKER_PLATFORM="linux/amd64"
DOCKER_NETWORK="scyllau-net"
# DOCKER_NETWORK="host"
# CLUSTER_SIZE=1
CLUSTER_SIZE=3

if [ "$(uname)" == "Darwin" ]; then
    echo "on macos"
    SCYLLA_BACKEND=epoll
    DOCKER_PLATFORM="linux/arm64/v8"
fi

checkNode() {
    ps_id=$( docker ps -f name="$1" --format "{{.ID}}" )
    echo "container id: $ps_id"

    if [[ "$ps_id" == "" ]]; then
        echo "FAILED!"
        docker ps -a

        echo
        echo "LOGS:"
        docker logs "$ps_id"

        echo
        echo "Removing ..."
        docker rm "$ps_id"

        exit 1
    fi    
}

status() {
    sleep 1
    docker exec -it "${1}" nodetool status  > /dev/null 2>&1
    return $?
}

printStatus() {
    docker exec -it "${1}" nodetool status
}

waitForNode() {
    echo "Waiting for ${1} to start"
    local i=0
    until status $1
    do
        printf "."
        if [ $i -gt 30 ]; then
            # one last attempt and shows status.  exits with error
            printStatus "${1}"
        fi
        i=$((i+1))
    done 
    printStatus "${1}"
    echo "ready"   
}

run() {
    echo "i=$i"
    [ -z "$1" ] && ( echo "Need node number" && exit 1)

    HOST_PORT=$((9041+i))
    CURR_NAME="$1"
    SEED_IP="${2:-}"
    echo "creating node ${CURR_NAME}"
    echo "  host port: ${HOST_PORT}"
    echo "  backend: ${SCYLLA_BACKEND}"
    echo "  platform: ${DOCKER_PLATFORM}"
    echo "  network: ${DOCKER_NETWORK}"
    if [ -z "${SEED_IP}" ]; then
        # the first node
        docker run -p ${HOST_PORT}:9042 --platform "${DOCKER_PLATFORM}" --network "${DOCKER_NETWORK}" --name "${CURR_NAME}" -v "${SCRIPTS_DIR}:/scripts" -d scylladb/scylla --reactor-backend="${SCYLLA_BACKEND}"
        # docker run --platform "${DOCKER_PLATFORM}" --network "${DOCKER_NETWORK}" --name "${CURR_NAME}" -h "$CURR_NAME" -v "$(pwd)/scripts:/scripts" -d scylladb/scylla --reactor-backend="${SCYLLA_BACKEND}" #--overprovisioned 1 --smp 1
    else
        echo "  seeds: ${SEED_IP}"
        docker run --platform "${DOCKER_PLATFORM}" --network "${DOCKER_NETWORK}" --name "${CURR_NAME}" -h "$CURR_NAME" -v "${SCRIPTS_DIR}:/scripts" -d scylladb/scylla --reactor-backend="${SCYLLA_BACKEND}" --seeds="${SEED_IP}" #--overprovisioned 1 --smp 1
    fi

    checkNode "${CURR_NAME}"
    waitForNode "${CURR_NAME}"
}

test() {
    echo 
    echo "======================== Testing =========================="
    if [ "$(uname)" == "Darwin" ]; then
        nc -zv 127.0.0.1 9042
    fi

    ${SCRIPTS_DIR}/exec "DESCRIBE CLUSTER"

    ${SCRIPTS_DIR}/exec "SELECT host_id FROM system.local;QUIT;"
}

up() {
    down
    echo

    if [ "${DOCKER_NETWORK}" != "host" ]; then
        if [ -z "$(docker network ls --filter name=^${DOCKER_NETWORK}$ --format="{{ .Name }}")" ]; then
        echo "Creating Docker network: ${DOCKER_NETWORK}"
        docker network create -d bridge "${DOCKER_NETWORK}"
        else
        echo "Docker network '${DOCKER_NETWORK}' already exists."
        fi
    fi

    local i=0
    for ((i=1; i<=CLUSTER_SIZE; i++))
    do
        CURR_NAME="${SCYLLA_NAME}$i"
        echo
        echo "======================== ${CURR_NAME} =========================="
        # NODE1_IP=""

        if [ "$i" -eq 1 ]; then
            run "$CURR_NAME"
        else
            echo "test"
            run "$CURR_NAME" "${SCYLLA_NAME}1" #"${NODE1_IP}"
        fi
    done
    test
}

down() {
    for ((i=1; i<=CLUSTER_SIZE; i++))
    do
        CURR_NAME="${SCYLLA_NAME}$i"
        echo "Stopping and removing ${CURR_NAME} ..."
        docker rm -f "${CURR_NAME}" || echo "No such container ${CURR_NAME}"
    done
}

cqlsh() {
    docker exec -it scyllaU1 cqlsh
}

bash() {
    docker exec -it scyllaU1 bash
}

action=$1
case $action in
  up)
    up
  ;;
  down)
    down
  ;;
  cqlsh)
    cqlsh
  ;;
  bash)
    bash
  ;;
esac
